name: 'build Linux'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version for the manual flow'
        required: true
        default: '1.2.3'
    workflow_call:
      inputs:
        version:
          description: 'The version for the manual flow'
          required: true
          type: string

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup .Net 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Build Linux App
        run: |
          cd CutCode.CrossPlatform
          dotnet publish -c Release -f net6.0 -r linux-x64
      - name: Archive Artifact
        run: |
          cd CutCode.CrossPlatform/bin/Release/net6.0/linux-x64
          tar -czvf -Path Linux.tar.gz release
      - name: Upload Archive
        if: ${{ github.event_name == 'workflow_dispatch' }}
        id: upload-release-asset
        uses: svenstaro/upload-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./CutCode.CrossPlatform/bin/Release/net6.0/linux-x64/Linux.tar.gz
          asset_name: LinuxBuild.tar.gz
          tag: ${{ github.events.inputs.version }}
    - name: Upload Archive
      if: ${{ github.event_name == 'workflow_call' }}
      id: upload-release-asset
      uses: svenstaro/upload-release-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./CutCode.CrossPlatform/bin/Release/net6.0/linux-x64/Linux.tar.gz
        asset_name: LinuxBuild.tar.gz
        tag: ${{ inputs.version }}